{% set name = "minuit2-split" %}
{% set version = "6-35-01" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", ".") }}

source:
  url: https://github.com/root-project/root/archive/v{{ version|replace(".","-") }}.tar.gz
  sha256: 6a7890b79231b94e20d5e6c4da64303b6a5fc30639359973c2fae566771fd81e
  patches:
    - 0001-mathcore_standalone.patch
    - 0002-Add-project-to-allow-Clang-features-to-be-detected.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('minuit2', max_pin='x.x') }}

outputs:
  - name: minuit2
    version: {{ version|replace("-", ".") }}
    build:
      script: bash ${RECIPE_DIR}/build_standalone.sh
    requirements:
      build:
        - cmake 3.20.*
        - make
        - {{ stdlib("c") }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      # conflicts with root due to same libs
      run_constrained:
        - root ==99999
    test:
      commands:
        - test -f ${PREFIX}/lib/libMinuit2${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/lib/libMinuit2Math${SHLIB_EXT}  # [unix]
        - cd math/minuit2/build/test/MnSim
        - |
          for binary in ../../bin/*; do
            # Fix up the run path of the macOS binaries
            export INSTALL_NAME_TOOL=$(find ${PREFIX}/bin -name '*install_name_tool' | head -n 1)  # [osx]
            ${INSTALL_NAME_TOOL} -add_rpath ${PREFIX}/lib ${binary}  # [osx]
            ${INSTALL_NAME_TOOL} -add_rpath @executable_path/../lib ${binary}  # [osx]
            # Fix up the run path of the Linux binaries
            patchelf --set-rpath $PREFIX/lib:${PWD}/../../lib ${binary}  # [linux]
            # Run the test
            ${binary}
          done
      requires:
        - patchelf  # [linux]
        - cctools  # [osx]
      source_files:
        - math/minuit2/build/bin/
        - math/minuit2/build/lib/libGaussSim.*
        - math/minuit2/build/test/MnSim/*.txt

  - name: minuit2_standalone
    version: {{ version|replace("-", ".") }}
    requirements:
      run:
        - {{ pin_subpackage('minuit2', exact=True) }}
      # Mark the standalone package as conflicting with ROOT
      run_constrained:
        - root ==99999
    test:
      commands:
        - test -f ${PREFIX}/lib/libMinuit2${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/lib/libMinuit2Math${SHLIB_EXT}  # [unix]

about:
  home: https://root.cern.ch/doc/master/Minuit2Page.html
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://root.cern.ch/root/htmldoc/guides/users-guide/ROOTUsersGuide.html#minuit2-package
  dev_url: https://github.com/root-project/root/
  summary: |
    This is the C++ Minuit2 fitter standalone edition, from the ROOT toolkit.
    For information about the Minuit2 fitter, please see the documentation in ROOT.
    This is not a Python frontend to Minuit2, which is provided by the iminuit package.
  description: |
    The Minuit2 library is a new object-oriented implementation, written in C++, of the popular
    MINUIT minimization package. These new version provides basically all the functionality
    present in the old Fortran version, with almost equivalent numerical accuracy and
    computational performances. Furthermore, it contains new functionality, like the possibility
    to set single side parameter limits or the FUMILI algorithm, which is an optimized method for
    least square and log likelihood minimizations. The package has been originally developed by
    M. Winkler and F. James. More information on the new C++ version can be found on the MINUIT
    Web Site. This is not a Python frontend to Minuit2, which is provided by the iminuit package.

extra:
  feedstock-name: minuit2
  recipe-maintainers:
    - mwittgen
    - brianv0
    - beckermr
